### ISSUE TITLE
Original Lampton code

### ISSUE THREAD

**Issue by jacmoe** [johangardhage/retro-gardens#1]
I saw your comment on Archive.org for the Gardens of Imagination book, and I did manage to get hold of the original code. A guy called Mike actually bought the book and sent me the code, after seeing my repository.
It can be found here, in the Original folder -> https://github.com/jacmoe/retrogardens.

**Comment by johangardhage** [comment]
Thanks Jacob!

I guess you mean the comment here:
https://archive.org/details/gardensofimagina00lamp

I think that the same Mike added a link to my github where I also do some
retro programming.
https://github.com/johangardhage/retro-gardens

--gajo

**Comment by jacmoe** [comment]
Ah, it was Mike who linked your repository, my bad!
Not the same Mike who managed to get me the code, though. Michael Coburn is his name. And much praise to him, because I've been looking for the code for years and years.
I bought the book in 1997 or 1998, and then (like a Normal Person) got rid of  the floppy disk during the dark ages of the naughties (2000s).
Anyway, the original - and extremely messy 1997-style C++ - code is available, finally :)
